apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo-voting-app
    name: postgres-pod
spec: 
  containers: 
    - 
      image: postgres:9.4
      name: postgres
      ports: 
        - 
          containerPort: 5432