--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: demo-voting-app
    name: db-service
  name: db
spec: 
  ports: 
    - 
      port: 5432
      targetPort: 5432
  selector: 
    app: demo-voting-app
    name: postgres-pod
