--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo-voting-app
    name: redis-pod
  name: redis-pod
spec: 
  containers: 
    - 
      image: redis
      name: redis
      ports: 
        - 
          containerPort: 6379
