--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo-voting-app
    name: result-app-pod
  name: result-app-pod
spec: 
  containers: 
    - 
      image: dockersamples/examplevotingapp_result
      name: result-app
      ports: 
        - 
          containerPort: 80
