--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo-voting-app
    name: voting-app-pod
    type: front-end
  name: voting-app-pod
spec: 
  containers: 
    - 
      image: dockersamples/examplevotingapp_vote
      name: voting-app
      ports: 
        - 
          containerPort: 80
